### ISSUE TITLE
Models, Api, and Error Handling System Design

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync#2]
This issue is for discussion of the Database Models, Api, Error Handling, and Authentication System design.

**Comment by iankronquist** [comment]
This is a giant issue. I'm going to split Auth into its own issue because I have some ideas.

**Comment by iankronquist** [comment]
Since we seem to be using knex we have no models. The API and error handling has been resolved with @tschuy's pr #4. This can be closed.
