### ISSUE TITLE
Decide on a (possibly revised) data structure

### ISSUE THREAD

**Issue by pop** [osuosl/timesync#30]
![Massive Issue/Discussion Ahead](https://media.giphy.com/media/Zsx8ZwmX3ajny/giphy.gif)
**Warning:** Massive Issue/Discussion Ahead

Some of the @osuosl/devs  ( @Kennric , @athai , @matthewrsj , @lucywyman , and I ) had a meeting about data structures and which may be better in the long vs short term. The discussion was spurred by the topic of...
### How do we best structure `GET /endpoint?archived=true` return data?

We thought of three structures that _could_ possibly work to display archived data (i.e., hitting the endpoint `GET /thing?archived=true`):
#### 1) List of list of objects

This is the most straight forward data structure. It is a list of objects in either chronological or reverse-chronological order.

Each object gives the end user essentially all data we store on the object (the id, the parent's id, etc) and lets the user sort things out (beyond the already chronologically sorted list of items).

``` javascript
[
  [
    {
      "thing":"foo",
      "id":1,
      "parent":null,
    },
    {
      "thing":"foo",
      "id":3,
      "parent":1,
    },
    {
      "thing":"foo",
      "id":5,
      "parent":3,
    },
  ],
  [
    {
      "thing":"bar",
      "id":2
      "parent":null,
    },
    {
      "thing":"bar",
      "id":4
      "parent":2,
    }
  ],
  [...],
]
```

**Advantages:**
- Simple data structure
- Can take advantage of list data-type to answer simple questions (how many times was X revised?)

**Disadvantages:**
- Gives send user the 'parent' field which is an example of our implementation creeping into the API specification.
#### 2) List of nested objects

``` javascript
[
  {
    "thing":"foo",
    "id":5
    "parent":
      {
        "thing":"foo",
        "id":3
        "parent":
          {
            "thing":"foo",
            "id":1,
            "parent":null,
          },
      },
  },
  {
    "thing":"bar",
    "id":4
    "parent":
      {
        "thing":"bar",
        "id":2
        "parent":null,
      },
  },
  {...},
]
```

**Advantages:**
- Logical and intuitive (structured data, not just a data structure)
- Obscures our implementation decision and allows others to implement things differently if they choose.

**Disadvantages:**
- Have to iterate over the entire object to get any information.
#### 3) List objects with a list of parent objects

This will put a list of the parent objects in the 'parent' field of a given archived object. The order of the parent objects is as yet undetermined but will be chronological or reverse-chronological.

``` javascript
[
  {
    "thing":"foo",
    "id":5
    "parent":
      [
        {
          "thing":"foo",
          "id":3
          "parent": 1
        },
        {
          "thing":"foo",
          "id":1,
          "parent":null,
        },
      ],
  },
  {
    "thing":"bar",
    "id":4
    "parent":
      [
        {
          "thing":"bar",
          "id":2
          "parent":null,
        },
      ],
  },
  {...},
]
```

**Advantages:**
- Essentially the middle-ground between the two previous options.

**Disadvantages:**
- Difficult to intuit; doesn't make obvious sense.
### The next problem: Consistent return types (question-mark?)

If we return a List of Objects, or a List of Lists of Objects, we ought to be consistent with our return types between returning archived and non-archived data. This brings up a problem which may require some fundamental changes that _could_ suck but _should_ mostly just involve wrapping return data to the user in a list or something to that extent. Anyway, _examples_:

These are what the return data would look like if we were consistent with our return types given the above option while hitting the `GET /thing` endpoint:
#### List of list of objects

``` javascript
[
  [
    {
      "thing":"foo",
      "id":5,
    },
  ],
  [
    {
      "thing":"bar",
      "id":4
    },
  ],
  [...]
]
```
#### List of Nested Objects & List Objects With a List of Parent Objects & The Status Quo (what we current return according to the docs)

``` javascript
[
  {
    "thing":"foo",
    "id":5,
  },
  {
    "thing":"bar",
    "id":4
  },
  {...},
]
```

**Note:** I do not include the parent field in this example data; we may give that to the user though, if we think it is useful
### Are we supposed to discuss something?

**Yes**

The topics of discussion for this issue include:
1. What data structure ought we return for `GET /endpoint?archived=true` response data.
2. What data structure ought we return for `GET /endpoint` response data.
3. Is the `?archived=true` parameter even the right approach? (this was brought up at the meatspace meeting in passing)

**Comment by pop** [comment]
So a lot happened in our weekly(ish) sprint(ish) meeting(not ish).

We voted and decided to use the third option (_List objects with a list of parent objects_). If that's where things ended our data would look like this for `GET /thing?archive=true`:

``` javascript
[
  {
    "thing":"foo",
    "id":5
    "parent":
      [
        {
          "thing":"foo",
          "id":3
          "parent": 1
        },
        {
          "thing":"foo",
          "id":1,
          "parent":null,
        },
      ],
  },
  {
    "thing":"bar",
    "id":4
    "parent":
      [
        {
          "thing":"bar",
          "id":2
          "parent":null,
        },
      ],
  },
  {...},
]
```

and this for `GET /thing`

```
[
  {
    "thing":"foo",
    "id":5,
  },
  {
    "thing":"bar",
    "id":4
  },
  {...},
]
```

**BUT** we threw around the idea of replacing the `id` field with `revision` (which goes up sequentially instead of being the raw id of the object) and a `uuid` field that is the same for every revision of an object -- anyway `GET /times?archive=true` would look like this:

``` javascript
[
  {
    "duration":12,
    "user": "example-user",
    "project": "ganeti",
    "activities": ["docs", "planning"],
    "notes":"Worked on documentation toward settings configuration.",
    "issue_uri":"https://github.com/osuosl/ganeti_webmgr/issues/40",
    "date_worked":2014-04-17,
    "created_at":2014-04-17,
    "updated_at":2015-04-19,
    "parents":
      [
        {
          "duration":9,
          "user": "example-user",
          "project": "ganeti",
          "activities": ["docs", "planning"],
          "notes":"Worked on documentation toward settings configuration.",
          "issue_uri":"https://github.com/osuosl/ganeti_webmgr/issues/40",
          "date_worked":2014-04-17,
          "created_at":2014-04-17,
          "updated_at":2015-04-18,
          "uuid": "<same fancy uuid>",
          "revision": 2
        },
        {
          "duration":3,
          "user": "example-user",
          "project": "ganeti",
          "activities": ["docs", "planning"],
          "notes":"Worked on documentation toward settings configuration.",
          "issue_uri":"https://github.com/osuosl/ganeti_webmgr/issues/40",
          "date_worked":2014-04-17,
          "created_at":2014-04-17,
          "updated_at":null,
          "uuid": "<same fancy uuid>",
          "revision": 1
        }
      ],
    "uuid": "<some fancy uuid>",
    "revision": 3
  },
  {...}
]
```

This change was made because it's a hassle to keep track of a new id every time you update an object. `uuid` field will exist in Project, Activity, and Time objects.

So yeah, now we get to implement this.

@devs @Kennric pls comment.

**Comment by Kennric** [comment]
This is looking pretty good. I have made a few comments on #28, but in general I think this is the correct structure to move forward with. +1
