### ISSUE TITLE
Create 'parameters' section of API docs

### ISSUE THREAD

**Issue by pop** [osuosl/timesync#36]
Right now the API docs are scattered in how they reveal to the user which parameters exists and which endpoints each parameter works for. I suggest we have a section titled 'Parameters' which clearly lays out:
- which parameters exists
- which endpoints they work for
- which parameters they can be combined with
- what they return
- any quirks the user should know

**Comment by Kennric** [comment]
Good idea. We did something like that for what's fresh. +1

**Comment by matthewrsj** [comment]
That would be great to have from a frontend development standpoint. +1

**Comment by athai** [comment]
I'm all for it. I had some difficulty finding parameters earlier, so this would definitely help with navigating the docs.

**Comment by matthewrsj** [comment]
Fixed by #39
