### ISSUE TITLE
Standardize parameter syntax

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/timesync#37]
Currently this exists

```
/times?user=:username
```

and so does this

```
/times/<time entry uuid>
```

We should use one or the other, preferably `<this syntax>` so as not to be confusing.

**Comment by pop** [comment]
@matthewrsj this is addressed in #36 , I know it's not in the title but I went through and got rid of all <variables> and replaced them with :variable_name (commit d416210a059782cf431bab66637a6c76b86606fe specifically)
