### ISSUE TITLE
Verify API docs mention that there are checks done on data

### ISSUE THREAD

**Issue by pop** [osuosl/timesync#4]
Update the documentation so it mentions the following functionality in TimeSync:
- Check that time/date is valid ISO timedate
- Check URI is a valid URI
- Check that activities exist
- Check that project exist
- Check owner of request == user in time entry (authorization not authentication)

**Comment by lucywyman** [comment]
Can this be closed?

**Comment by pop** [comment]
I think so. @osuosl/devs @Kennric is this an ongoing issue or should it be closed?

**Comment by MorganEPatch** [comment]
Yes, it was corrected by #6, apparently the issue was simply never closed.
