### ISSUE TITLE
Question about API docs clarity

### ISSUE THREAD

**Issue by matthewrsj** [osuosl/timesync#49]
Does the following paragraph apply to all POST `<endpoint>/<uuid-or-slug>`? If it does, it shouldn't just be under [POST /times/](https://github.com/osuosl/timesync/blob/develop/source/draft_api.rst#post-times):

```
Likewise, if you'd like to edit an existing object, POST to /<object name>/<slug> (or 
for time objects, /times/<uuid>) with a JSON body. The object only needs to contain
the part that is being updated. The response body will contain the saved object, as 
shown above. 
```

Same question for this paragraph under [POST /projects/](https://github.com/osuosl/timesync/blob/develop/source/draft_api.rst#post-projects-slug):

```
If a value of "" (an empty string) or [] (an empty array) are passed as values for a 
string or array optional field (check the :ref:`model docs<draft_model>`), the value 
will be set to the empty string/array. If a value of null or undefined is provided, the 
current value of the object will be used.
```

And does the second paragraph mean you can only pass null or undefined to optional fields to leave them un-updated? What about just not passing them at all like is suggested in the first paragraph?

**Comment by matthewrsj** [comment]
According to the implementation, paragraph 2 doesn't apply to POST /times/ at all:

```
{
  "status": 400,
  "error": "Bad object",
  "text": "Field notes of time should be string but was sent as null"
}
```

**Comment by matthewrsj** [comment]
There seems to be an inconsistency here as well. I tried to POST to `projects/ps` (ps is a pymesync slug) to update it with this:

```
{
    "auth": {
        "type": "password",
        "username": "<my-username>",
        "password": "<my-password>"
    },
    "object": {
        "slugs":["pymesync", "ps", "pyme", "psync"],
        "uri":null
    }
}
```

and got this back:

```
{
  "status": 400,
  "error": "Bad object",
  "text": "Field uri of project should be string but was sent as null"
}
```

but it worked when I took out `"uri":null`

The [models doc](https://github.com/osuosl/timesync/blob/develop/source/draft_model.rst#projects) says that `uri` is optional so it should allow null according to paragraph 2.

**Comment by matthewrsj** [comment]
Per conversation in December 2015 Summit, fields will **not** be nullable. If a user does not want to update a field for **any** endpoint, they will not pass that field in the update POST.

**Comment by MorganEPatch** [comment]
> Does the following paragraph apply to all POST `<endpoint>/<uuid-or-slug>`? If it does, it shouldn't just be under POST /times/:
> 
> Likewise, if you'd like to edit an existing object, POST to `/<object name>/<slug>` (or 
> for time objects, `/times/<uuid>`) with a JSON body. The object only needs to contain
> the part that is being updated. The response body will contain the saved object, as 
> shown above. 

It may be poorly worded, but the intent is that that doesn't _follow_ `/times` as much as _precede_ the `/:endpoint/:uuid-or-slug` sections. That may need to be clarified.

> If a value of "" (an empty string) or [](an empty array) are passed as values for a 
> string or array optional field (check the :ref:`model docs<draft_model>`), the value 
> will be set to the empty string/array. If a value of null or undefined is provided, the 
> current value of the object will be used.
> 
> And does the second paragraph mean you can only pass null or undefined to optional fields to leave them un-updated? What about just not passing them at all like is suggested in the first paragraph?

That's been changed in new PRs to say "a value of undefined" instead of "null or undefined". A value of `undefined` in Javascript is identical to not passing a value.
