### ISSUE TITLE
Meetings Notes 2016-01-29

### ISSUE THREAD

**Issue by pop** [osuosl/timesync#54]
# User Crud

`/Things` = `/activities`, `/times` or `/projects`:
### Project
- member
  - Can Create, Get, Update, Delete while a member of a given project,
  - Can Get, Update, and Delete times after being a member of a given project.
- spectator:
  - Views all projects / activities, and all times of a given project.
- manager
### Sitewide
- admin

**Comment by matthewrsj** [comment]
I think the Sitewide roles also included spectator and member.

Does this change user CRUD? Because this https://github.com/osuosl/timesync/blob/develop/source/draft_users.rst#post-users doesn't seem to address how to set someone's permissions.

**Comment by MorganEPatch** [comment]
These have now been completed in #55 and #56, closing.
