### ISSUE TITLE
Give general authentication failure on malformed username

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync#72]
Currently, the API gives two different errors for authentication failure: `Invalid Username` and `Authentication Failure`. The `Invalid Username` error is for when a username contains invalid characters such as spaces, but it could be easily misinterpreted as an error that should be thrown when a **nonexistent** username is provided.

Distinguishing between a nonexistent username and an invalid password is [bad practice](https://www.owasp.org/index.php/Authentication_Cheat_Sheet#Authentication_and_Error_Messages), so the docs should either be made clearer on when `Invalid Username` should be thrown or the `Invalid Username` error should be removed and its triggering conditions moved to the more general `Authentication Failure` error.

**Comment by MorganEPatch** [comment]
I'll see how we can clarify, but the answer is, Invalid Username is used when _registering_ an account, and your username doesn't follow the requirements (only certain characters, etc.); Authentication Failure is used when any error occurs while _logging in_, including the username or password not existing.

**Comment by pop** [comment]
This might be a docs problem more than an implementation.  It's possible we _drifted_ a bit from the API when writing an implementation.  Either way, clarifying the docs and double checking the implementation is a good idea.

**Comment by MorganEPatch** [comment]
I believe the implementation is correct and follows the behavior I described; I think the docs just need to be clarified to ensure it doesn't seem like Invalid Username is an authentication error.

**Comment by MorganEPatch** [comment]
On further review, the docs clearly state:

"**Invalid Username**: This error is returned when *creating* a new user and a username with invalid
characters is provided."

"**Authentication Failure**: This error is returned when authentication fails *for any reason.*"
(Emphasis mine)

Thus I feel it's clear that Invalid Username is a *registration* failure, Authentication Failure is an *authentication* error (including attempting to log in as a user who doesn't exist).
