### ISSUE TITLE
Add user roles

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync#81]
Roles would be a useful feature to have because it would extend the concept of metadata in the current version of the specification and make it more useful. We could still keep the metadata field around for extra information, but being able to assign users to different roles could make some things easier to implement and use:

### Easier permission management:

Instead of assigning each user their own set of global permissions and project permissions, users could be given roles and then the permissions of each role could be customized. For example, a group of people working on related projects could all be assigned to a single role that encompasses member permissions for all of those projects.

We could either replace the current permission model with role permissions, or the two could co-exist. Either way, roles could drastically reduce the amount of effort needed to assign and change permissions.

### Sorting users and times by role

timesync-frontend-flask currently has this capability to an extent (Filtering by the contents of a user's metadata), but adding support for querying users and times by role would make this feature much easier to implement.

**Comment by MorganEPatch** [comment]
Superseded by #83.
